#
#Makefile for the Linux gt filesystem routines.
#
obj-$(CONFIG_GT_FS) += gt.o
#KDIR += /lib/modules/$(shell uname -r)/build
#PWD += $(shell pwd)
gt-y := dir.o file.o inode.o namei.o super.o
#default:
#	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
