/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 *
 * Copyright (c) 2013 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtMultimedia.h"

#line 26 "/home/pythoner/workspace_hank/python/pyqt5/PyQt-gpl-5.1/sip/QtMultimedia/qmediametadata.sip"
#include <qmediametadata.h>
#line 29 "/home/pythoner/workspace_hank/python/pyqt5/PyQt-gpl-5.1/QtMultimedia/sipQtMultimediaQMediaMetaData.cpp"

#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 33 "/home/pythoner/workspace_hank/python/pyqt5/PyQt-gpl-5.1/QtMultimedia/sipQtMultimediaQMediaMetaData.cpp"


extern "C" {static PyObject *varget_QMediaMetaData_AlbumArtist(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_AlbumArtist(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::AlbumArtist);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_AlbumTitle(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_AlbumTitle(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::AlbumTitle);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_AudioBitRate(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_AudioBitRate(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::AudioBitRate);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_AudioCodec(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_AudioCodec(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::AudioCodec);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Author(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Author(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Author);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_AverageLevel(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_AverageLevel(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::AverageLevel);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_CameraManufacturer(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_CameraManufacturer(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::CameraManufacturer);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_CameraModel(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_CameraModel(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::CameraModel);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Category(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Category(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Category);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ChannelCount(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ChannelCount(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ChannelCount);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ChapterNumber(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ChapterNumber(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ChapterNumber);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Comment(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Comment(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Comment);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Composer(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Composer(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Composer);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Conductor(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Conductor(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Conductor);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Contrast(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Contrast(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Contrast);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ContributingArtist(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ContributingArtist(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ContributingArtist);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Copyright(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Copyright(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Copyright);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_CoverArtImage(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_CoverArtImage(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::CoverArtImage);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_CoverArtUrlLarge(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_CoverArtUrlLarge(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::CoverArtUrlLarge);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_CoverArtUrlSmall(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_CoverArtUrlSmall(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::CoverArtUrlSmall);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Date(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Date(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Date);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_DateTimeDigitized(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_DateTimeDigitized(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::DateTimeDigitized);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_DateTimeOriginal(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_DateTimeOriginal(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::DateTimeOriginal);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Description(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Description(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Description);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_DeviceSettingDescription(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_DeviceSettingDescription(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::DeviceSettingDescription);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_DigitalZoomRatio(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_DigitalZoomRatio(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::DigitalZoomRatio);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Director(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Director(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Director);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Duration(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Duration(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Duration);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Event(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Event(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Event);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ExposureBiasValue(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ExposureBiasValue(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ExposureBiasValue);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ExposureMode(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ExposureMode(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ExposureMode);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ExposureProgram(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ExposureProgram(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ExposureProgram);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ExposureTime(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ExposureTime(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ExposureTime);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_FNumber(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_FNumber(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::FNumber);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Flash(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Flash(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Flash);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_FocalLength(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_FocalLength(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::FocalLength);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_FocalLengthIn35mmFilm(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_FocalLengthIn35mmFilm(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::FocalLengthIn35mmFilm);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSAltitude(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSAltitude(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSAltitude);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSAreaInformation(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSAreaInformation(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSAreaInformation);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSDOP(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSDOP(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSDOP);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSImgDirection(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSImgDirection(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSImgDirection);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSImgDirectionRef(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSImgDirectionRef(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSImgDirectionRef);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSLatitude(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSLatitude(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSLatitude);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSLongitude(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSLongitude(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSLongitude);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSMapDatum(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSMapDatum(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSMapDatum);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSProcessingMethod(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSProcessingMethod(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSProcessingMethod);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSSatellites(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSSatellites(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSSatellites);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSSpeed(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSSpeed(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSSpeed);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSStatus(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSStatus(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSStatus);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSTimeStamp(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSTimeStamp(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSTimeStamp);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSTrack(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSTrack(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSTrack);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GPSTrackRef(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GPSTrackRef(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GPSTrackRef);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_GainControl(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_GainControl(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::GainControl);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Genre(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Genre(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Genre);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ISOSpeedRatings(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ISOSpeedRatings(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ISOSpeedRatings);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Keywords(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Keywords(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Keywords);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Language(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Language(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Language);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_LeadPerformer(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_LeadPerformer(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::LeadPerformer);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_LightSource(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_LightSource(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::LightSource);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Lyrics(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Lyrics(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Lyrics);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_MediaType(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_MediaType(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::MediaType);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_MeteringMode(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_MeteringMode(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::MeteringMode);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Mood(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Mood(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Mood);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Orientation(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Orientation(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Orientation);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ParentalRating(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ParentalRating(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ParentalRating);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_PeakValue(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_PeakValue(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::PeakValue);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_PixelAspectRatio(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_PixelAspectRatio(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::PixelAspectRatio);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_PosterImage(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_PosterImage(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::PosterImage);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_PosterUrl(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_PosterUrl(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::PosterUrl);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Publisher(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Publisher(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Publisher);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_RatingOrganization(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_RatingOrganization(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::RatingOrganization);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Resolution(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Resolution(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Resolution);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_SampleRate(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_SampleRate(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::SampleRate);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Saturation(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Saturation(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Saturation);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_SceneCaptureType(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_SceneCaptureType(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::SceneCaptureType);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Sharpness(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Sharpness(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Sharpness);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Size(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Size(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Size);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_SubTitle(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_SubTitle(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::SubTitle);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Subject(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Subject(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Subject);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_SubjectDistance(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_SubjectDistance(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::SubjectDistance);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_ThumbnailImage(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_ThumbnailImage(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::ThumbnailImage);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Title(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Title(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Title);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_TrackCount(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_TrackCount(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::TrackCount);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_TrackNumber(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_TrackNumber(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::TrackNumber);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_UserRating(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_UserRating(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::UserRating);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_VideoBitRate(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_VideoBitRate(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::VideoBitRate);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_VideoCodec(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_VideoCodec(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::VideoCodec);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_VideoFrameRate(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_VideoFrameRate(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::VideoFrameRate);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_WhiteBalance(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_WhiteBalance(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::WhiteBalance);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Writer(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Writer(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Writer);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}


extern "C" {static PyObject *varget_QMediaMetaData_Year(void *, PyObject *, PyObject *);}
static PyObject *varget_QMediaMetaData_Year(void *, PyObject *, PyObject *)
{
    static PyObject *sipPy = NULL;
    const QString*sipVal;

    if (sipPy)
    {
        Py_INCREF(sipPy);
        return sipPy;
    }

    sipVal = new QString(QMediaMetaData::Year);

    sipPy = sipConvertFromNewType(const_cast<QString *>(sipVal), sipType_QString, NULL);
    Py_XINCREF(sipPy);

    return sipPy;
}

sipVariableDef variables_QMediaMetaData[] = {
    {ClassVariable, sipName_AlbumArtist, (PyMethodDef *)varget_QMediaMetaData_AlbumArtist, NULL, NULL, NULL},
    {ClassVariable, sipName_AlbumTitle, (PyMethodDef *)varget_QMediaMetaData_AlbumTitle, NULL, NULL, NULL},
    {ClassVariable, sipName_AudioBitRate, (PyMethodDef *)varget_QMediaMetaData_AudioBitRate, NULL, NULL, NULL},
    {ClassVariable, sipName_AudioCodec, (PyMethodDef *)varget_QMediaMetaData_AudioCodec, NULL, NULL, NULL},
    {ClassVariable, sipName_Author, (PyMethodDef *)varget_QMediaMetaData_Author, NULL, NULL, NULL},
    {ClassVariable, sipName_AverageLevel, (PyMethodDef *)varget_QMediaMetaData_AverageLevel, NULL, NULL, NULL},
    {ClassVariable, sipName_CameraManufacturer, (PyMethodDef *)varget_QMediaMetaData_CameraManufacturer, NULL, NULL, NULL},
    {ClassVariable, sipName_CameraModel, (PyMethodDef *)varget_QMediaMetaData_CameraModel, NULL, NULL, NULL},
    {ClassVariable, sipName_Category, (PyMethodDef *)varget_QMediaMetaData_Category, NULL, NULL, NULL},
    {ClassVariable, sipName_ChannelCount, (PyMethodDef *)varget_QMediaMetaData_ChannelCount, NULL, NULL, NULL},
    {ClassVariable, sipName_ChapterNumber, (PyMethodDef *)varget_QMediaMetaData_ChapterNumber, NULL, NULL, NULL},
    {ClassVariable, sipName_Comment, (PyMethodDef *)varget_QMediaMetaData_Comment, NULL, NULL, NULL},
    {ClassVariable, sipName_Composer, (PyMethodDef *)varget_QMediaMetaData_Composer, NULL, NULL, NULL},
    {ClassVariable, sipName_Conductor, (PyMethodDef *)varget_QMediaMetaData_Conductor, NULL, NULL, NULL},
    {ClassVariable, sipName_Contrast, (PyMethodDef *)varget_QMediaMetaData_Contrast, NULL, NULL, NULL},
    {ClassVariable, sipName_ContributingArtist, (PyMethodDef *)varget_QMediaMetaData_ContributingArtist, NULL, NULL, NULL},
    {ClassVariable, sipName_Copyright, (PyMethodDef *)varget_QMediaMetaData_Copyright, NULL, NULL, NULL},
    {ClassVariable, sipName_CoverArtImage, (PyMethodDef *)varget_QMediaMetaData_CoverArtImage, NULL, NULL, NULL},
    {ClassVariable, sipName_CoverArtUrlLarge, (PyMethodDef *)varget_QMediaMetaData_CoverArtUrlLarge, NULL, NULL, NULL},
    {ClassVariable, sipName_CoverArtUrlSmall, (PyMethodDef *)varget_QMediaMetaData_CoverArtUrlSmall, NULL, NULL, NULL},
    {ClassVariable, sipName_Date, (PyMethodDef *)varget_QMediaMetaData_Date, NULL, NULL, NULL},
    {ClassVariable, sipName_DateTimeDigitized, (PyMethodDef *)varget_QMediaMetaData_DateTimeDigitized, NULL, NULL, NULL},
    {ClassVariable, sipName_DateTimeOriginal, (PyMethodDef *)varget_QMediaMetaData_DateTimeOriginal, NULL, NULL, NULL},
    {ClassVariable, sipName_Description, (PyMethodDef *)varget_QMediaMetaData_Description, NULL, NULL, NULL},
    {ClassVariable, sipName_DeviceSettingDescription, (PyMethodDef *)varget_QMediaMetaData_DeviceSettingDescription, NULL, NULL, NULL},
    {ClassVariable, sipName_DigitalZoomRatio, (PyMethodDef *)varget_QMediaMetaData_DigitalZoomRatio, NULL, NULL, NULL},
    {ClassVariable, sipName_Director, (PyMethodDef *)varget_QMediaMetaData_Director, NULL, NULL, NULL},
    {ClassVariable, sipName_Duration, (PyMethodDef *)varget_QMediaMetaData_Duration, NULL, NULL, NULL},
    {ClassVariable, sipName_Event, (PyMethodDef *)varget_QMediaMetaData_Event, NULL, NULL, NULL},
    {ClassVariable, sipName_ExposureBiasValue, (PyMethodDef *)varget_QMediaMetaData_ExposureBiasValue, NULL, NULL, NULL},
    {ClassVariable, sipName_ExposureMode, (PyMethodDef *)varget_QMediaMetaData_ExposureMode, NULL, NULL, NULL},
    {ClassVariable, sipName_ExposureProgram, (PyMethodDef *)varget_QMediaMetaData_ExposureProgram, NULL, NULL, NULL},
    {ClassVariable, sipName_ExposureTime, (PyMethodDef *)varget_QMediaMetaData_ExposureTime, NULL, NULL, NULL},
    {ClassVariable, sipName_FNumber, (PyMethodDef *)varget_QMediaMetaData_FNumber, NULL, NULL, NULL},
    {ClassVariable, sipName_Flash, (PyMethodDef *)varget_QMediaMetaData_Flash, NULL, NULL, NULL},
    {ClassVariable, sipName_FocalLength, (PyMethodDef *)varget_QMediaMetaData_FocalLength, NULL, NULL, NULL},
    {ClassVariable, sipName_FocalLengthIn35mmFilm, (PyMethodDef *)varget_QMediaMetaData_FocalLengthIn35mmFilm, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSAltitude, (PyMethodDef *)varget_QMediaMetaData_GPSAltitude, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSAreaInformation, (PyMethodDef *)varget_QMediaMetaData_GPSAreaInformation, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSDOP, (PyMethodDef *)varget_QMediaMetaData_GPSDOP, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSImgDirection, (PyMethodDef *)varget_QMediaMetaData_GPSImgDirection, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSImgDirectionRef, (PyMethodDef *)varget_QMediaMetaData_GPSImgDirectionRef, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSLatitude, (PyMethodDef *)varget_QMediaMetaData_GPSLatitude, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSLongitude, (PyMethodDef *)varget_QMediaMetaData_GPSLongitude, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSMapDatum, (PyMethodDef *)varget_QMediaMetaData_GPSMapDatum, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSProcessingMethod, (PyMethodDef *)varget_QMediaMetaData_GPSProcessingMethod, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSSatellites, (PyMethodDef *)varget_QMediaMetaData_GPSSatellites, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSSpeed, (PyMethodDef *)varget_QMediaMetaData_GPSSpeed, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSStatus, (PyMethodDef *)varget_QMediaMetaData_GPSStatus, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSTimeStamp, (PyMethodDef *)varget_QMediaMetaData_GPSTimeStamp, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSTrack, (PyMethodDef *)varget_QMediaMetaData_GPSTrack, NULL, NULL, NULL},
    {ClassVariable, sipName_GPSTrackRef, (PyMethodDef *)varget_QMediaMetaData_GPSTrackRef, NULL, NULL, NULL},
    {ClassVariable, sipName_GainControl, (PyMethodDef *)varget_QMediaMetaData_GainControl, NULL, NULL, NULL},
    {ClassVariable, sipName_Genre, (PyMethodDef *)varget_QMediaMetaData_Genre, NULL, NULL, NULL},
    {ClassVariable, sipName_ISOSpeedRatings, (PyMethodDef *)varget_QMediaMetaData_ISOSpeedRatings, NULL, NULL, NULL},
    {ClassVariable, sipName_Keywords, (PyMethodDef *)varget_QMediaMetaData_Keywords, NULL, NULL, NULL},
    {ClassVariable, sipName_Language, (PyMethodDef *)varget_QMediaMetaData_Language, NULL, NULL, NULL},
    {ClassVariable, sipName_LeadPerformer, (PyMethodDef *)varget_QMediaMetaData_LeadPerformer, NULL, NULL, NULL},
    {ClassVariable, sipName_LightSource, (PyMethodDef *)varget_QMediaMetaData_LightSource, NULL, NULL, NULL},
    {ClassVariable, sipName_Lyrics, (PyMethodDef *)varget_QMediaMetaData_Lyrics, NULL, NULL, NULL},
    {ClassVariable, sipName_MediaType, (PyMethodDef *)varget_QMediaMetaData_MediaType, NULL, NULL, NULL},
    {ClassVariable, sipName_MeteringMode, (PyMethodDef *)varget_QMediaMetaData_MeteringMode, NULL, NULL, NULL},
    {ClassVariable, sipName_Mood, (PyMethodDef *)varget_QMediaMetaData_Mood, NULL, NULL, NULL},
    {ClassVariable, sipName_Orientation, (PyMethodDef *)varget_QMediaMetaData_Orientation, NULL, NULL, NULL},
    {ClassVariable, sipName_ParentalRating, (PyMethodDef *)varget_QMediaMetaData_ParentalRating, NULL, NULL, NULL},
    {ClassVariable, sipName_PeakValue, (PyMethodDef *)varget_QMediaMetaData_PeakValue, NULL, NULL, NULL},
    {ClassVariable, sipName_PixelAspectRatio, (PyMethodDef *)varget_QMediaMetaData_PixelAspectRatio, NULL, NULL, NULL},
    {ClassVariable, sipName_PosterImage, (PyMethodDef *)varget_QMediaMetaData_PosterImage, NULL, NULL, NULL},
    {ClassVariable, sipName_PosterUrl, (PyMethodDef *)varget_QMediaMetaData_PosterUrl, NULL, NULL, NULL},
    {ClassVariable, sipName_Publisher, (PyMethodDef *)varget_QMediaMetaData_Publisher, NULL, NULL, NULL},
    {ClassVariable, sipName_RatingOrganization, (PyMethodDef *)varget_QMediaMetaData_RatingOrganization, NULL, NULL, NULL},
    {ClassVariable, sipName_Resolution, (PyMethodDef *)varget_QMediaMetaData_Resolution, NULL, NULL, NULL},
    {ClassVariable, sipName_SampleRate, (PyMethodDef *)varget_QMediaMetaData_SampleRate, NULL, NULL, NULL},
    {ClassVariable, sipName_Saturation, (PyMethodDef *)varget_QMediaMetaData_Saturation, NULL, NULL, NULL},
    {ClassVariable, sipName_SceneCaptureType, (PyMethodDef *)varget_QMediaMetaData_SceneCaptureType, NULL, NULL, NULL},
    {ClassVariable, sipName_Sharpness, (PyMethodDef *)varget_QMediaMetaData_Sharpness, NULL, NULL, NULL},
    {ClassVariable, sipName_Size, (PyMethodDef *)varget_QMediaMetaData_Size, NULL, NULL, NULL},
    {ClassVariable, sipName_SubTitle, (PyMethodDef *)varget_QMediaMetaData_SubTitle, NULL, NULL, NULL},
    {ClassVariable, sipName_Subject, (PyMethodDef *)varget_QMediaMetaData_Subject, NULL, NULL, NULL},
    {ClassVariable, sipName_SubjectDistance, (PyMethodDef *)varget_QMediaMetaData_SubjectDistance, NULL, NULL, NULL},
    {ClassVariable, sipName_ThumbnailImage, (PyMethodDef *)varget_QMediaMetaData_ThumbnailImage, NULL, NULL, NULL},
    {ClassVariable, sipName_Title, (PyMethodDef *)varget_QMediaMetaData_Title, NULL, NULL, NULL},
    {ClassVariable, sipName_TrackCount, (PyMethodDef *)varget_QMediaMetaData_TrackCount, NULL, NULL, NULL},
    {ClassVariable, sipName_TrackNumber, (PyMethodDef *)varget_QMediaMetaData_TrackNumber, NULL, NULL, NULL},
    {ClassVariable, sipName_UserRating, (PyMethodDef *)varget_QMediaMetaData_UserRating, NULL, NULL, NULL},
    {ClassVariable, sipName_VideoBitRate, (PyMethodDef *)varget_QMediaMetaData_VideoBitRate, NULL, NULL, NULL},
    {ClassVariable, sipName_VideoCodec, (PyMethodDef *)varget_QMediaMetaData_VideoCodec, NULL, NULL, NULL},
    {ClassVariable, sipName_VideoFrameRate, (PyMethodDef *)varget_QMediaMetaData_VideoFrameRate, NULL, NULL, NULL},
    {ClassVariable, sipName_WhiteBalance, (PyMethodDef *)varget_QMediaMetaData_WhiteBalance, NULL, NULL, NULL},
    {ClassVariable, sipName_Writer, (PyMethodDef *)varget_QMediaMetaData_Writer, NULL, NULL, NULL},
    {ClassVariable, sipName_Year, (PyMethodDef *)varget_QMediaMetaData_Year, NULL, NULL, NULL},
};


pyqt5ClassTypeDef sipTypeDef_QtMultimedia_QMediaMetaData = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_NAMESPACE,
        sipNameNr_QMediaMetaData,
        {0}
    },
    {
        sipNameNr_QMediaMetaData,
        {0, 0, 1},
        0, 0,
        0, 0,
        91, variables_QMediaMetaData,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0,
    0
};
