TEMPLATE = app
QT -= gui
QT += xml
CONFIG += warn_on release
target.path = /usr/local/python3/bin
INSTALLS += target
INCLUDEPATH += /home/pythoner/workspace_hank/python/pyqt5/PyQt-gpl-5.1/pyrcc
VPATH = /home/pythoner/workspace_hank/python/pyqt5/PyQt-gpl-5.1/pyrcc
HEADERS = rcc.h
SOURCES = rcc.cpp main.cpp